name: Test Manifest Creation
on: workflow_dispatch  # This allows manual trigger from GitHub UI

env:
  IMAGE_NAME: "shieldauth/shield"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  test-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create and push manifest
        run: |
          # Enable experimental features for manifest support
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          
          # Set the version you want to test
          VERSION="v0.1.8-alpha"
          
          # Create and push version manifest
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${VERSION} \
            ${{ env.IMAGE_NAME }}:${VERSION}-amd64 \
            ${{ env.IMAGE_NAME }}:${VERSION}-arm64
          
          # Create and push latest manifest
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:latest-amd64 \
            ${{ env.IMAGE_NAME }}:latest-arm64
